### ISSUE TITLE
CTRL doesn't work on Mac OS

### ISSUE THREAD

**Issue by jollytoad** [mdavoodi/codenav-for-bitbucket-issues#2]
I like the look of this plugin, although it's currently no use to Mac users as CTRL clicking within a browser just opens the context menu. Would be useful if CMD could be used as an alternative.

**Comment by mdavoodi** [comment]
We've overhauled the whole plugin, with a lot of bugfixes and reworks. We've changed it so that you now just click on the class to be able to view the definitions. It felt a lot more intuitive this way. You can check out the changeset here:

https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.codenav/server/versionhistory

Let me know if you can give it a shot and give the new build some feedback!

I'm going to mark this issue as closed now that we don't use CTRL anymore.
